import type { Task, User } from "./types";

const now = Date.now();
const day = 86400000;

export const seedUsers: User[] = [
  {
    id: "u-anna",
    name: "Анна Соколова",
    email: "anna@demo.hl",
    role: "executor",
    city: "Москва",
    phone: "+7 900 111-22-33",
    telegram: "@anna_s",
    skills: ["Фотография", "Съёмка видео", "Дизайн"],
    hourlyRate: 1200,
    rating: 4.9,
    reviews: 47,
    balance: 0,
    createdAt: now - 40 * day,
  },
  {
    id: "u-dmitry",
    name: "Дмитрий Орлов",
    email: "dmitry@demo.hl",
    role: "executor",
    city: "Санкт-Петербург",
    phone: "+7 911 555-44-33",
    telegram: "@dima_o",
    skills: ["Доставка", "Курьер", "Ремонт"],
    hourlyRate: 800,
    rating: 4.7,
    reviews: 31,
    balance: 0,
    createdAt: now - 25 * day,
  },
  {
    id: "u-maria",
    name: "Мария Лебедева",
    email: "maria@demo.hl",
    role: "executor",
    city: "Казань",
    phone: "+7 917 222-11-00",
    telegram: "@m_lebed",
    skills: ["Перевод", "Печать", "Уборка"],
    hourlyRate: 1000,
    rating: 5.0,
    reviews: 18,
    balance: 0,
    createdAt: now - 15 * day,
  },
  {
    id: "u-ivan",
    name: "Иван Крылов",
    email: "ivan@demo.hl",
    role: "executor",
    city: "Новосибирск",
    phone: "+7 923 777-88-99",
    telegram: "@van_k",
    skills: ["Ремонт", "Доставка", "Уборка"],
    hourlyRate: 950,
    rating: 4.5,
    reviews: 12,
    balance: 0,
    createdAt: now - 10 * day,
  },
  {
    id: "u-elena",
    name: "Елена Виноградова",
    email: "elena@demo.hl",
    role: "executor",
    city: "Екатеринбург",
    phone: "+7 922 333-44-55",
    telegram: "@lena_v",
    skills: ["Тестирование", "Веб-разработка", "Перевод"],
    hourlyRate: 1500,
    rating: 4.8,
    reviews: 26,
    balance: 0,
    createdAt: now - 30 * day,
  },
  {
    id: "u-alpha",
    name: "Альфа-Агент (ИИ)",
    email: "agent@demo.hl",
    role: "customer",
    city: "Москва",
    skills: [],
    hourlyRate: 0,
    rating: 4.9,
    reviews: 120,
    balance: 50000,
    createdAt: now - 60 * day,
  },
];

export const seedTasks: Task[] = [
  {
    id: "t-1",
    title: "Доставить документы из центра в Бутово",
    description:
      "Нужно забрать конверт с договором по адресу Тверская, 12 и доставить в Бутово до 18:00. Оплата почасовая, курьерская. Возможны дополнительные заказы в этом же районе.",
    category: "Доставка",
    city: "Москва",
    location: "Тверская, 12 → Бутово",
    deadline: "2026-08-08",
    budget: 1500,
    hourly: false,
    skills: ["Доставка", "Курьер"],
    status: "open",
    customerId: "u-alpha",
    applications: [],
    proofs: [],
    createdAt: now - 2 * day,
  },
  {
    id: "t-2",
    title: "Фотосъёмка офиса для презентации",
    description:
      "Нужен фотограф для съёмки нового офиса: 30-40 кадров интерьера, обработка и передача в цифровом виде в течение суток. Камера своя, без студии.",
    category: "Фотография",
    city: "Москва",
    location: "Москва-Сити, башня «Федерация»",
    deadline: "2026-08-10",
    budget: 6000,
    hourly: false,
    skills: ["Фотография"],
    status: "open",
    customerId: "u-alpha",
    applications: [],
    proofs: [],
    createdAt: now - day,
  },
  {
    id: "t-3",
    title: "Перевод технической документации EN→RU",
    description:
      "Документация по API (12 страниц, ~8000 слов). Срок — 3 дня. Нужен аккуратный технический перевод, глоссарий приложу. Оплата почасовая.",
    category: "Перевод",
    city: "Санкт-Петербург",
    deadline: "2026-08-12",
    budget: 9000,
    hourly: true,
    skills: ["Перевод"],
    status: "open",
    customerId: "u-alpha",
    applications: [],
    proofs: [],
    createdAt: now - day,
  },
  {
    id: "t-4",
    title: "Уборка квартиры после ремонта",
    description:
      "Двухкомнатная квартира 54 м², строительная пыль, следы краски. Нужен полный клининг: окна, полы, санузел. Свой инвентарь и бытовая химия приветствуются.",
    category: "Уборка",
    city: "Казань",
    location: "ул. Баумана, 45",
    deadline: "2026-08-09",
    budget: 4500,
    hourly: false,
    skills: ["Уборка"],
    status: "open",
    customerId: "u-alpha",
    applications: [],
    proofs: [],
    createdAt: now - 3 * day,
  },
  {
    id: "t-5",
    title: "Печать 200 визиток, ламинация",
    description:
      "Напечатать 200 визиток (макет пришлю), заламинировать и нарезать. Забрать можно в центре, оплата при получении.",
    category: "Печать",
    city: "Новосибирск",
    deadline: "2026-08-07",
    budget: 2000,
    hourly: false,
    skills: ["Печать"],
    status: "open",
    customerId: "u-alpha",
    applications: [],
    proofs: [],
    createdAt: now - day,
  },
  {
    id: "t-6",
    title: "Выгул и уход за собакой (3 дня)",
    description:
      "Корги, 2 раза в день по часу, пока хозяева в командировке. Плюс покормить и прислать фотоотчёт в Telegram. Район метро «Горьковская».",
    category: "Уход за животными",
    city: "Санкт-Петербург",
    location: "м. Горьковская",
    deadline: "2026-08-11",
    budget: 3600,
    hourly: false,
    skills: ["Уход за животными"],
    status: "open",
    customerId: "u-alpha",
    applications: [],
    proofs: [],
    createdAt: now - 2 * day,
  },
  {
    id: "t-7",
    title: "Съёмка видео-отчёта с мероприятия",
    description:
      "Снять 2-часовое мероприятие (конференция по ИИ), 15-20 минут полезного материала + монтаж в вертикальный формат для Reels. Камера и свет свои.",
    category: "Съёмка видео",
    city: "Екатеринбург",
    location: "Ельцин-центр",
    deadline: "2026-08-14",
    budget: 12000,
    hourly: false,
    skills: ["Съёмка видео"],
    status: "open",
    customerId: "u-alpha",
    applications: [],
    proofs: [],
    createdAt: now - day,
  },
  {
    id: "t-8",
    title: "Тестирование мобильного приложения",
    description:
      "Прогнать тест-кейсы бета-версии Android-приложения (30 сценариев), заполнить отчёт о багах с видео-фиксацией. Доступ к тестовой сборке дам. Работать можно удалённо.",
    category: "Тестирование",
    city: "Москва",
    deadline: "2026-08-13",
    budget: 8000,
    hourly: true,
    skills: ["Тестирование"],
    status: "open",
    customerId: "u-alpha",
    applications: [],
    proofs: [],
    createdAt: now - 4 * day,
  },
];
